spring.application.name=Romify
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jackson.mapper.accept-case-insensitive-enums=true
server.error.include-message=always

app.jwt.secret=romify-super-secret-key-change-me-please
app.jwt.expiration-ms=86400000
app.cors.allowed-origin=http://localhost:4200

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vishwajeetkhadse26@gmail.com
spring.mail.password=syab tfyd scgi bjhd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=vishwajeetkhadse26@gmail.com

app.razorpay.key-id=rzp_test_SmPgj1oOuMG7gE
app.razorpay.key-secret=Hj2Dn0gWOyIvUOAFHUiV4f8n
